language: php

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - dnsutils
      - libpcap-dev

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

# Compile
before_script:
  - phpize && ./configure && make

# Run PHPs run-tests.php
script: sudo TEST_PHP_ARGS="-q --show-out" make test
